project_name: sp-cli
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates:
    - synfm/cli-test:{{.Tag}}
  dockerfile: Dockerfile