name: Release

on:
  push:
    tags:
      - '*'

env:
  REF: ${{ github.event.inputs.tag || github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: synfm
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
